theme = "hugo-coder"
baseURL = "https://petejon.es/"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Pete Jones"
title = "Pete Jones"
disqusshortname = ""
pluralizelisttitles = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[blackfriday]
	fractions = false

[markup]
  [markup.highlight]
    codeFences = false
  [markup.goldmark.renderer]
      unsafe = true

[params]
    author = "Pete Jones"
    info = "Social scientist sometimes studying fictional characters and sometimes studying real people"
    description = "Pete Jones"
    keywords = "blog,academic,personal"
    avatarurl = "img/pj_anim.png"

    favicon_32 = "img/icon.png"
    favicon_16 = "img/icon.png"

    hidecredits = false
    hidecopyright = false
	rtl = false
    math = true

# Social links
[[params.social]]
    name = "E-mail"
    icon = "fas fa-envelope"
    weight = 1
    url = "mailto:pete@petejon.es"
    target = "_blank"
	
[[params.social]]
    name = "Mastodon"
    icon = "fab fa-mastodon"
    weight = 2
    rel = "me"
    url = "https://hcommons.social/@petejones"
    target = "_blank"
	
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 3
    url = "https://github.com/pj398/"
    target = "_blank"
	
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/pete-jones-13b955105"
    target = "_blank"

[[params.social]]
    name = "ResearchGate"
    icon = "fab fa-researchgate"
    weight = 5
    url = "https://researchgate.net/profile/Pete_Jones6"
    target = "_blank"

# [[params.social]]
#     name = "Google Scholar"
#     icon = "fa-brands fa-google-scholar"
#     weight = 6
#     url = "https://scholar.google.com/citations?user=-GMiAW8AAAAJ&hl=en"
#     target = "_blank"
	
# Menu links
[[menu.main]]
    name = "Home"
    weight = 1
    url  = "/"

[[menu.main]]
    name = "Research"
    weight = 2
    url  = "/research/"
	
[[menu.main]]
    name = "Contact"
    weight = 3
    url  = "/contact/"	

[[menu.main]]
    name = "Blog"
    weight = 4
    url  = "/posts/"	
